version: '3.8'

services:
    mssql: 
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - SA_PASSWORD=Suporte59@.!
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes:
            - ././mssql:/var/opt/mssql/data   
        mem_limit: 
            512m
        container_name: 
            mssql
        expose:
          - 1433

    rabbitmq:
        image: rabbitmq:3.8.26-management-alpine
        command: rabbitmq-server
        container_name: rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
            - ././rabbitmq/etc/:/etc/rabbitmq/
            - ././rabbitmq/data/:/var/lib/rabbitmq/
            - ././rabbitmq/logs/:/var/log/rabbitmq/
        expose:
          - 15672

    mongodb:
        image : mongo
        container_name: mongodb
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - ././mongodb:/data/db
        ports:
        - 27017:27017
        restart: unless-stopped
        mem_limit: 
            512m
        expose:
          - 27017
    
    apigateway:
        container_name: apigateway
        environment:
            SecretKey: 1130f66f-591f-4f1c-a748-f1f9a1c7c43a
        ports:
            - 7000:80
        depends_on:
            - rabbitmq        
        build:
            context: .
            dockerfile: Web.BootCampFidelidade.HttpAggregator\Dockerfile

    wallet.api:
        image: elvysferrari/wallet.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8001
        ports:
            - 8001:8001
        mem_limit: 
            512m
        depends_on:
            - mssql        
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Wallet.API\Dockerfile

    bonification.api:
        image: elvysferrari/bonification.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8002
        ports:
            - 8002:8002
        mem_limit: 
            512m
        depends_on:
            - mssql    
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Bonification.API\Dockerfile    
            
    ransom.api:
        image: elvysferrari/ransom.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8003
        ports:
            - 8003:8003
        mem_limit: 
            512m
        depends_on:
            - mssql   
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Ransom.API\Dockerfile   
            
    extract.api:
        image: elvysferrari/extract.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8004
        ports:
            - 8004:8004
        mem_limit: 
            512m
        depends_on:
            - mssql
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Extract.API\Dockerfile

    promotion.api:
        image: elvysferrari/promotion.api  
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DOCKER_ENVIRONMENT=true
            - ASPNETCORE_URLS=http://+:8005
        ports:
            - 8005:8005
        mem_limit: 
            512m
        depends_on:
            - mongodb
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Promotion.API\Dockerfile    
    