version: '3.8'

services:
    db: 
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - SA_PASSWORD=Suporte59@.!
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes:
            - ${APPDATA}/dados:/var/opt/mssql/data   
        container_name: 
            db
        expose:
          - 1433
    wallet.api:
        image: wallet.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8001
        ports:
            - 8001:8001
        depends_on:
            - db
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Wallet.API\Dockerfile
    bonification.api:
        image: bonification.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8002
        ports:
            - 8002:8002
        depends_on:
            - db
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Bonification.API\Dockerfile
    