version: '3.8'

services:
    mssql: 
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - SA_PASSWORD=Suporte59@.!
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes:
            - ./mssql/:/var/opt/mssql/data   
        container_name: 
            mssql
        expose:
          - 1433

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - '5672:5672'
            - '15672:15672'
        expose:
          - 15672

    mongodb:        
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./mongodb:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        mem_limit: 
            512m
        expose:
          - 27017
    
    apigateway:
        image: fernando2022/apigateway.api        
        environment:
            - SecretKey=1130f66f-591f-4f1c-a748-f1f9a1c7c43a
            - Database=DBFidelidade
            - DbUser=SA
            - Password=Suporte59@.!
            - Datasource=host.docker.internal, 1433
            - MongoDbDatabase=promotionsdb
            - MongoDbDatasource=mongodb://host.docker.internal:27017
        ports:
            - 7000:80
        depends_on:
            - rabbitmq        
        build:
            context: .
            dockerfile: Web.BootCampFidelidade.HttpAggregator\Dockerfile

    wallet.api:
        image: fernando2022/wallet.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8001
          - Database=DBFidelidade
          - DbUser=SA
          - Password=Suporte59@.!
          - Datasource=host.docker.internal, 1433
        ports:
            - 8001:8001
        mem_limit: 
            512m
        depends_on:
            - mssql        
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Wallet.API\Dockerfile

    bonification.api:
        image: fernando2022/bonification.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8002
          - Database=DBFidelidade
          - DbUser=SA
          - Password=Suporte59@.!
          - Datasource=host.docker.internal, 1433
        ports:
            - 8002:8002
        mem_limit: 
            512m
        depends_on:
            - mssql    
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Bonification.API\Dockerfile    
            
    ransom.api:
        image: fernando2022/ransom.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8003
          - Database=DBFidelidade
          - DbUser=SA
          - Password=Suporte59@.!
          - Datasource=host.docker.internal, 1433
        ports:
            - 8003:8003
        mem_limit: 
            512m
        depends_on:
            - mssql   
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Ransom.API\Dockerfile   
            
    extract.api:
        image: fernando2022/extract.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8004
          - Database=DBFidelidade
          - DbUser=SA
          - Password=Suporte59@.!
          - Datasource=host.docker.internal, 1433
        ports:
            - 8004:8004
        mem_limit: 
            512m
        depends_on:
            - mssql
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Extract.API\Dockerfile

    promotion.api:
        image: fernando2022/promotion.api  
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DOCKER_ENVIRONMENT=true
            - ASPNETCORE_URLS=http://+:8005
            - MongoDbDatabase=promotionsdb
            - MongoDbDatasource=mongodb://host.docker.internal:27017
        ports:
            - 8005:8005
        mem_limit: 
            512m
        depends_on:
            - mongodb
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Promotion.API\Dockerfile

    order.api:
        image: fernando2022/order.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8004
          - Database=DBFidelidade
          - DbUser=SA
          - Password=Suporte59@.!
          - Datasource=host.docker.internal, 1433
        ports:
            - 8006:8006
        mem_limit: 
            512m
        depends_on:
            - mssql
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Order.API\Dockerfile
    