version: '3.8'

services:
    db: 
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - SA_PASSWORD=Suporte59@.!
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"
        volumes:
            - ${APPDATA}/dados:/var/opt/mssql/data   
        container_name: 
            db
        expose:
          - 1433
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
        - PUID=1000
        - PGID=1000
        volumes:
        - /home/barry/mongodb/database:/data/db
        ports:
        - 27017:27017
        restart: unless-stopped
        expose:
          - 27017
    wallet.api:
        image: elvysferrari/wallet.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8001
        ports:
            - 8001:8001
        depends_on:
            - db        
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Wallet.API\Dockerfile
    bonification.api:
        image: elvysferrari/bonification.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8002
        ports:
            - 8002:8002
        depends_on:
            - db    
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Bonification.API\Dockerfile            
    ransom.api:
        image: elvysferrari/ransom.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8003
        ports:
            - 8003:8003
        depends_on:
            - db   
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Ransom.API\Dockerfile             
    extract.api:
        image: elvysferrari/extract.api  
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - DOCKER_ENVIRONMENT=true
          - ASPNETCORE_URLS=http://+:8004
        ports:
            - 8004:8004
        depends_on:
            - db
        build:
            context: .
            dockerfile: FrwkBootCampFidelidade.Extract.API\Dockerfile
    promotion.api:
            image: elvysferrari/promotion.api  
            environment:
              - ASPNETCORE_ENVIRONMENT=Development
              - DOCKER_ENVIRONMENT=true
              - ASPNETCORE_URLS=http://+:8005
            ports:
                - 8005:8005
            depends_on:
                - mongodb
            build:
                context: .
                dockerfile: FrwkBootCampFidelidade.Promotion.API\Dockerfile    
    